In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [10]:
df = pd.read_csv('/content/ev_washington_state.csv', on_bad_lines= 'skip')

In [ ]:
# Não sou daqueles que retrocedem

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300142 entries, 0 to 300141
Data columns (total 16 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         300142 non-null  object
 1   County                                             300127 non-null  object
 2   City                                               300127 non-null  object
 3   State                                              300142 non-null  object
 4   Postal Code                                        300127 non-null  float64
 5   Model Year                                         300142 non-null  int64
 6   Make                                               300142 non-null  object
 7   Model                                              300142 non-null  object
 8   Electric Vehicle Type                              300142 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  300142 non-null  object
 10  Electric Range                                     300107 non-null  float64
 11  Legislative District                               299352 non-null  float64
 12  DOL Vehicle ID                                     300142 non-null  int64
 13  Vehicle Location                                   300118 non-null  object
 14  Electric Utility                                   300127 non-null  object
 15  2020 GEOID                                         300127 non-null  float64
dtypes: float64(4), int64(2), object(10)
memory usage: 36.6+ MB

In [4]:
df.describe()

,Postal Code,Model Year,Electric Range,Legislative District,DOL Vehicle ID,2020 GEOID
count,300127.000000,300142.000000,300107.000000,299352.000000,3.001420e+05,3.001270e+05
mean,98175.788819,2022.389056,36.148437,28.719230,2.516250e+08,5.296688e+10
std,2669.566595,3.095011,75.443498,14.886897,6.211185e+07,1.696036e+09
min,1030.000000,1999.000000,0.000000,1.000000,4.385000e+03,1.001020e+09
25%,98052.000000,2021.000000,0.000000,17.000000,2.287301e+08,5.303301e+10
50%,98134.000000,2023.000000,0.000000,32.000000,2.686437e+08,5.303303e+10
75%,98391.000000,2025.000000,32.000000,42.000000,2.851263e+08,5.305394e+10
max,99403.000000,2027.000000,337.000000,49.000000,4.791150e+08,6.601095e+10

In [7]:
df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 GEOID
0,3FMTK3SU8P,King,Seattle,WA,98177.0,2023,FORD,MUSTANG MACH-E,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,32.0,254622924,POINT (-122.37238 47.74068),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
1,JM3KKEHA8S,Thurston,Yelm,WA,98597.0,2025,MAZDA,CX-90,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,26.0,2.0,277791643,POINT (-122.60735 46.94239),PUGET SOUND ENERGY INC,5.306701e+10
2,5YJ3E1EB8J,King,Sammamish,WA,98075.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,41.0,347418676,POINT (-122.03539 47.61344),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
3,JHMZC5F12K,Island,Oak Harbor,WA,98277.0,2019,HONDA,CLARITY,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,47.0,10.0,223620701,POINT (-122.64682 48.29077),PUGET SOUND ENERGY INC,5.302997e+10
4,1C4RJXN65R,Kitsap,Bremerton,WA,98312.0,2024,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21.0,26.0,256402674,POINT (-122.65223 47.57192),PUGET SOUND ENERGY INC,5.303508e+10

In [ ]:
# Alguém disse uma vez que ciência de dados se trata de extrair conhecimento de dados desorgânizados, e de fato isto é verdade.

In [21]:
contagem_marcas = df.Make.value_counts().reset_index().sort_values(by= 'count', ascending= False)

In [13]:
# Quais As marcas mais de carros elétricos mais comprada em Whashigton?

In [23]:
contagem_marcas.head(10)

        Make   count
0      TESLA  122291
1  CHEVROLET   20218
2       FORD   15997
3     NISSAN   15994
4        KIA   14897
5     TOYOTA   14374
6    HYUNDAI   12581
7        BMW   12395
8     RIVIAN   10150
9      VOLVO    8255

In [26]:
contagem_marcas.iloc[1:10]

        Make  count
1  CHEVROLET  20218
2       FORD  15997
3     NISSAN  15994
4        KIA  14897
5     TOYOTA  14374
6    HYUNDAI  12581
7        BMW  12395
8     RIVIAN  10150
9      VOLVO   8255

In [47]:
diferenca = sum(list(contagem_marcas.iloc[1: 10]['count'])) - contagem_marcas.at[0, 'count']

In [50]:
print(f"Valor que a Tesla possui amais que todos os 9 colocados no racking de 10 maiores vendedores: {diferenca}")

Valor que a Tesla possui amais que todos os 9 colocados no racking de 10 maiores vendedores: 2570

In [ ]:
# Será que existe relação entre o local e a marca?
# Por que a Tesla é a marca mais vendida

In [ ]:
# Ask
# Get
# Explorer
# Model
# Comunicate

# Qual o tamanho da frota de carros elétricos de washington?
# Qual a fatia do mercado que a Tesla possui?

In [59]:
tamanho_frota = contagem_marcas['count'].sum()
qntd_tesla = contagem_marcas.at[0, 'count']

parcela_tesla = (qntd_tesla / tamanho_frota) * 100

In [62]:
print(f"Parcela Tesla: {parcela_tesla:.2f}%")

Parcela Tesla: 40.74%

#Qual o tamanho da Frota nacional de carros elétricos?

In [69]:
print(f"A minha estimatica de quantidade de veículos elétricos que os EUA possuem: {tamanho_frota * 50:,} de unidades")

A minha estimatica de quantidade de veículos elétricos que os EUA possuem: 15,007,100 de unidades

#Como as outras marcas tem avançado anualmente no setor?

In [70]:
df.columns

Index(['VIN (1-10)', 'County', 'City', 'State', 'Postal Code', 'Model Year',
       'Make', 'Model', 'Electric Vehicle Type',
       'Clean Alternative Fuel Vehicle (CAFV) Eligibility', 'Electric Range',
       'Legislative District', 'DOL Vehicle ID', 'Vehicle Location',
       'Electric Utility', '2020 GEOID'],
      dtype='object')

In [73]:
df.groupby()

TypeError: You have to supply one of 'by' and 'level'

In [78]:
df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 GEOID
0,3FMTK3SU8P,King,Seattle,WA,98177.0,2023,FORD,MUSTANG MACH-E,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,32.0,254622924,POINT (-122.37238 47.74068),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
1,JM3KKEHA8S,Thurston,Yelm,WA,98597.0,2025,MAZDA,CX-90,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,26.0,2.0,277791643,POINT (-122.60735 46.94239),PUGET SOUND ENERGY INC,5.306701e+10
2,5YJ3E1EB8J,King,Sammamish,WA,98075.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,41.0,347418676,POINT (-122.03539 47.61344),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
3,JHMZC5F12K,Island,Oak Harbor,WA,98277.0,2019,HONDA,CLARITY,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,47.0,10.0,223620701,POINT (-122.64682 48.29077),PUGET SOUND ENERGY INC,5.302997e+10
4,1C4RJXN65R,Kitsap,Bremerton,WA,98312.0,2024,JEEP,WRANGLER,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,21.0,26.0,256402674,POINT (-122.65223 47.57192),PUGET SOUND ENERGY INC,5.303508e+10

In [79]:
# df[df["Make"] == marca].value_counts()

VIN (1-10)  County     City            State  Postal Code  Model Year  Make   Model     Electric Vehicle Type           Clean Alternative Fuel Vehicle (CAFV) Eligibility             Electric Range  Legislative District  DOL Vehicle ID  Vehicle Location             Electric Utility                                                            2020 GEOID
SFZRE11B98  San Juan   Friday Harbor   WA     98250.0      2008        TESLA  ROADSTER  Battery Electric Vehicle (BEV)  Eligibility unknown as battery range has not been researched  0.0             40.0                  267100207       POINT (-123.01648 48.53448)  BONNEVILLE POWER ADMINISTRATION||ORCAS POWER & LIGHT COOP                   5.305596e+10    1
5YJ3E1E19J  King       Kirkland        WA     98034.0      2018        TESLA  MODEL 3   Battery Electric Vehicle (BEV)  Clean Alternative Fuel Vehicle Eligible                       215.0           1.0                   283858760       POINT (-122.20928 47.71124)  PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)                               5.303302e+10    1
5YJ3E1EA0H  King       Kent            WA     98030.0      2017        TESLA  MODEL 3   Battery Electric Vehicle (BEV)  Clean Alternative Fuel Vehicle Eligible                       220.0           47.0                  135149584       POINT (-122.19976 47.37483)  PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)                               5.303303e+10    1
                                              98032.0      2017        TESLA  MODEL 3   Battery Electric Vehicle (BEV)  Clean Alternative Fuel Vehicle Eligible                       220.0           33.0                  274930547       POINT (-122.23741 47.3807)   PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)                               5.303303e+10    1
                       Seattle         WA     98199.0      2017        TESLA  MODEL 3   Battery Electric Vehicle (BEV)  Clean Alternative Fuel Vehicle Eligible                       220.0           36.0                  104996139       POINT (-122.39418 47.6392)   CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)                                5.303301e+10    1
                                                                                                                                                                                                                                                                                                                                                                    ..
5YJ3E1EA0J  Chelan     Manson          WA     98831.0      2018        TESLA  MODEL 3   Battery Electric Vehicle (BEV)  Clean Alternative Fuel Vehicle Eligible                       215.0           12.0                  233506500       POINT (-120.16034 47.8854)   PUD NO 1 OF CHELAN COUNTY                                                   5.300796e+10    1
            Benton     Kennewick       WA     99337.0      2018        TESLA  MODEL 3   Battery Electric Vehicle (BEV)  Clean Alternative Fuel Vehicle Eligible                       215.0           8.0                   289331605       POINT (-119.14482 46.18763)  BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF BENTON COUNTY                  5.300501e+10    1
                       Benton City     WA     99320.0      2018        TESLA  MODEL 3   Battery Electric Vehicle (BEV)  Clean Alternative Fuel Vehicle Eligible                       215.0           16.0                  278198693       POINT (-119.48756 46.26543)  BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF BENTON COUNTY                  5.300501e+10    1
5YJ3E1EA0H  Spokane    Airway Heights  WA     99001.0      2017        TESLA  MODEL 3   Battery Electric Vehicle (BEV)  Clean Alternative Fuel Vehicle Eligible                       220.0           6.0                   273478341       POINT (-117.59311 47.6443)   BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||INLAND POWER & LIGHT COMPANY  5.306301e+10    1
            Snohomish  Stanwood        WA     98292.0      2017        TESLA  MODEL 3   Battery Electric Vehicle (BEV)  Clean Alternative Fuel Vehicle Eligible                       220.0           10.0                  297589883       POINT (-122.37265 48.24159)  PUGET SOUND ENERGY INC                                                      5.306105e+10    1
Name: count, Length: 121878, dtype: int64

In [91]:
unidades_marcas = df.groupby("Model Year").agg({"Model": "count"}).reset_index().sort_values(by= 'Model', ascending= False).iloc[0:10]

In [93]:
unidades_marcas

    Model Year  Model
18        2023  61487
19        2024  49111
21        2026  38472
20        2025  36561
17        2022  29963
16        2021  20685
13        2018  13745
15        2020  12016
14        2019  10666
12        2017   8353